#!/bin/sh
STD=c++17
CXXFLAGS=-std=${STD}

echo "Correctness:"
cppcheck --language=c++ --std=${STD} --quiet $*

CHECKS=clang-diagnostic-*,clang-analyzer-*,bugprone-*,cert-*
clang-tidy -quiet -checks=$CHECKS  $* -- $CXXFLAGS

echo -e "\nCoding standards:"

CHECKS=-clang*,modernize-*,llvm-*,misc-*,readability-*,cppcoreguidelines-*,-cppcoreguidelines-owning-memory,-modernize-use-trailing-return-type,-readability-named-parameter,-llvm-header-guard,-llvm-include-order
clang-tidy -quiet -checks=$CHECKS  $* -- $CXXFLAGS

